[package]
name = "physostegia"
version = "0.1.0"
authors = ["tokizuoh"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
regex = "1.4.2"
anyhow = "1.0.34"
colored = "2"
structopt = "0.3.20"
itertools = "0.9.0"
